# This is a basic workflow to help you get started with Actions

name: Test issue 4#

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: SFTP Deploy
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  

      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      # SFTP Upload
      - name: Akamai GN SFTP uploader
        uses: DanJ210/akamai-gn-sftp-upload-action@3.0.0
        with:
            host: 'cdnassetsgolfnow.sftp.upload.akamai.com'
            username: 'sshacs'
            localDir: '.'
            remoteDir: '/1535440/www.golfnow.com_TEST'
            privateKey: ${{ secrets.AKAMAI_RSA }}
            compress: true
            exclude: '.git*/**/*,.git*,web.config,*.ps1,*.md'
            forceUpload: false                    # Optional, Force uploading all files, Default to false(upload only newer files).
            removeExtraFilesOnServer: false       # Optional, Remove extra files on server. Default to false.
            